image: cr.gfx.cafe/build/img/nodejs:latest
site:
  stage: build
  cache:
    - key:
        files:
          - yarn.lock
          - docs/yarn.lock
        prefix: yarn
      paths:
        - node_modules/
        - docs/node_modules/
    - paths:
        - docs/.docusaurus/
  script:
    - npx yarn install
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - site
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
