image: cr.gfx.cafe/build/img/nodejs:latest
pages:
  stage: deploy
  cache:
    - key:
        files:
          - yarn.lock
        prefix: yarn
      paths:
        - node_modules/
  script:
    - sh install-mdbook.sh
    - npx yarn install
    - npm run mdbook --arg=build && rm -rf ./public/book/* && cp -r ./docs/book/* ./public/book/*
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
