image: cr.gfx.cafe/build/img/nodejs:latest
site:
  stage: build
  cache:
    - key:
        files:
          - yarn.lock
          - docs/yarn.lock
        prefix: yarn
      paths:
        - node_modules/
        - docs/node_modules/
    - paths:
        - docs/.docusaurus/
  script:
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - npx yarn install
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - site
  script:
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages-github:
  stage: deploy
  dependencies:
    - site
  script:
    - git config --global credential.helper '!f() { sleep 1; echo "username=gfxlabs"; echo "password=$GITHUB_TOKEN"; }; f'
    - git config --global user.email "bot@gfx.cafe"
    - git config --global user.name "gfx.cafe"
    - git clone https://github.com/gfx-labs/ip-app-pages.git
    - cp -r dist ip-app-pages/$CI_COMMIT_SHORT_SHA
    - rm -rf ip-app-pages/docs
    - cp -r dist ip-app-pages/docs
    - cd ip-app-pages
    - git add -A && git commit -m "added commit $CI_COMMIT_SHORT_SHA"
    - git push
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
